version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: php.dockerfile
      # dockerfile: php.dockerfile
    container_name: php_app
    restart: unless-stopped
    volumes:
      - ./php_src:/var/www/html:delegated
    environment:
      - APP_ENV=development
    entrypoint: ['php', '/var/www/html/artisan', 'octane:start', "--host=0.0.0.0"]
    ports:
      - "3000:8000"  # Adjust the port as needed
